### ISSUE TITLE
Use the metric ID for the label instead of fullPath

### ISSUE THREAD

**Issue by philipwalton** [daliborgogic/nuxt-vitals#2]
I know it's probably not quite clear why ID is needed, but it's actually really important—if you're sending this data to Google Analytics—that you have a dimension you can use to drill down into each individual metric occurrence. Without this, you won't be able to create a histogram or report on anything other than the metric average (and even then you won't be able to report on the average for CLS).

Regarding the use of `fullPath`, if what you want is the URL path of the page that was loaded when this metric was tracked, you can use the [`page`](https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#page) dimension (or [`dp`](https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#dp) in the measurement protocol):

```js
async function sendToAnalytics(fullPath, metric) {
  const { name, delta, id, entries } = metric
  let opts = {
    ec: 'Web Vitals',
    ea: name,
    el: id,
    // Google Analytics metrics must be integers, so the value is rounded.
    ev: parseInt(delta),
    dp: fullPath,
    ni: true
  }

  // ...
}
```

Note: I also set the `ni` param to `true`. Not sure if this was a mistake or not, but setting this to `false` will make your bounce rate go to zero (unless that's what you want).

**Comment by daliborgogic** [comment]
@philipwalton Yes, main reason  why I replace `id` with `fullPath` is to know from which route is event fired. Will invest time in `collect` documentation to check. New field for me. Thank you for your time and explanation!

**Comment by philipwalton** [comment]
No problem!

BTW, I'm working on putting together some examples showing how to build histograms from GA data collected in the format [outlined here](https://github.com/GoogleChrome/web-vitals#send-the-results-to-google-analytics). Hopefully that'll make it more clear why an ID dimension is important!
