### ISSUE TITLE
Build Modules

### ISSUE THREAD

**Issue by daliborgogic** [daliborgogic/nuxt-vitals#4]
Usually, modules are only required during development and build time. Using `buildModules` helps to make production startup faster and also significantly decreasing `node_modules` size for production deployments. 

**NOTE**: If we are going to offer using `buildModules` need to mention that this feature is only available since Nuxt **v2.9.** Older users should upgrade Nuxt or use the `modules` section.

**Comment by PizzaPete** [comment]
What needs to be done for this issue? Only readme changes or also some code changes?

**Comment by daliborgogic** [comment]
Hi @PizzaPete, only readme changes. This module is only required during the build. Starting at `v2.9` we now have option to specify `buildModules`. So in `readme` needs to be changed `modules` to `buildModules` and `npm` command with flag `-D` to install module as `devDependecies`. And for user that don't use `v2.9.+` to upgrade Nuxt or to use the `module` as it now in `readme`.

**Comment by PizzaPete** [comment]
@daliborgogic thanks for the info. I'll see if I can pick this one up in the upcoming days.
